-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 18:57:44 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo` ;

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`OrgUnit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`OrgUnit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`OrgUnit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  `lead` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_OrgUnit_OrgUnit1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `demo`.`OrgUnit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_OrgUnit_OrgUnit1_idx` ON `demo`.`OrgUnit` (`parent_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `demo`.`OrgUnit` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `demo`.`OrgUnit` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`Project` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`Project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `org_unit_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Project_OrgUnit1`
    FOREIGN KEY (`org_unit_id`)
    REFERENCES `demo`.`OrgUnit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `project_id_UNIQUE` ON `demo`.`Project` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `demo`.`Project` (`name` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Project_OrgUnit1_idx` ON `demo`.`Project` (`org_unit_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`RoleType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`RoleType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`RoleType` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `demo`.`RoleType` (`id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `demo`.`RoleType` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`RoleSubType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`RoleSubType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`RoleSubType` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RoleType_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_RoleSubType_RoleType1`
    FOREIGN KEY (`RoleType_id`)
    REFERENCES `demo`.`RoleType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `demo`.`RoleSubType` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_RoleSubType_RoleType1_idx` ON `demo`.`RoleSubType` (`RoleType_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`Budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`Budget` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`Budget` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `baselined` TINYINT(1) NULL COMMENT '	',
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ProjectBudget_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `demo`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `demo`.`Budget` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_ProjectBudget_Project1_idx` ON `demo`.`Budget` (`project_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`Resource` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`Resource` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProjectBudget_id` INT UNSIGNED NOT NULL,
  `RoleSubType_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ProjectBudgetResource_ProjectBudget1`
    FOREIGN KEY (`ProjectBudget_id`)
    REFERENCES `demo`.`Budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resource_RoleSubType1`
    FOREIGN KEY (`RoleSubType_id`)
    REFERENCES `demo`.`RoleSubType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_ProjectBudgetResource_ProjectBudget1_idx` ON `demo`.`Resource` (`ProjectBudget_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Resource_RoleSubType1_idx` ON `demo`.`Resource` (`RoleSubType_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `demo`.`Forecast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo`.`Forecast` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `demo`.`Forecast` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `month` INT UNSIGNED NOT NULL,
  `fte` DECIMAL(2) UNSIGNED NOT NULL,
  `ProjectBudgetResource_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Forecast_ProjectBudgetResource1`
    FOREIGN KEY (`ProjectBudgetResource_id`)
    REFERENCES `demo`.`Resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `demo`.`Forecast` (`id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Forecast_ProjectBudgetResource1_idx` ON `demo`.`Forecast` (`ProjectBudgetResource_id` ASC);

SHOW WARNINGS;
GRANT ALL ON `demo`.* TO 'gk';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
